= Floating Point Model Documentation
:toc:
:toclevels: 3
:sectnums:
:stem: latexmath

== B3: Rounding - sign, LSB, guard bit, sticky bit

Aharoni et al.

== B8: Vicinity of Rounding Boundaries

=== Description

This model targets numbers that are on the edge of a rounding boundary. These boundaries may vary depending on the rounding mode. These numbers include floating-point numbers and mid-points between floating-point numbers. In order to target the vicinity of these numbers, we test the following constraints on the extra bits of the intermediate result:

1. All values of extra-bits in the range [000…00001, 000…00011]
2. All values of extra-bits in the range [111…11100, 111…11111]

For each value selected above, test all the combinations on the LSB of the significand, the guard bit, and the sticky bit (if the number of extra bits is not finite).

*Number of tests:* 6E3

*Precisions Supported:* `BF_16`, `FP_16`, `FP_32`, `FP_64`, `FP_128`, `INT32`, `UINT32`, `INT64`, `UINT64`

*Operations Supported*: `ADD`, `SUB`, `MUL`, `DIV`, `FMA` (all flavors), `CFI`, `CIF`, `CFF`

*Unsupported Operations*: `REM`, `SQRT`

*Rounding Mode*: Round Nearest to Even, Round Min Magnitude, Round Min, Round Max, Round Near to Max Magnitude

== Implementation

=== Definitions

`Intermediate Result`:: The result of the given operation evaluated to full (theoretically infinite) precision before it is rounded
`LSB`:: Least significant bit of the intermediate result according to the mantissa length
`Guard Bit`:: The first bit after lsb in an intermediate result
`Sticky Bit`:: Bitwise or of the remaining bit after the guard bit

== Background

We want to verify that values are being correctly rounded when they are very close to a rounding target. In this range of outputs, it is common to see hardware optimizations, like jamming bits into the last value of a sticky, or other techniques to avoid the infinite precision nature of floating point math. We also end up showing that rounding calculations are correct in all rounding modes at these extreme numbers of extra bits.

For division, we also get very good tests for numbers that are extremely close to being accurate results, but just barely not there. This should stress the hardware performing a division to be exactly correct and not make a mistake with ramifications only found many bits into the extra bits.

== Test Procedure

=== General Procedure

We generate the target extra bit patterns which vary in length depending on the operation and format, and guard, lsb, and sign parings. Together, these will cover all possible rounding boundaries. Exponents are randomized within reason, and all operations are ensured to be in their effective operation.

=== Division

Division is probably the most interesting case here. We start with the observation that to get arbitrarily many bits out of a division result in integer arithmetic, we use stem:[\left\lfloor\frac{a\cdot2^n}{b}\right\rfloor] where stem:[n] is the desired number of bits. Now, if we want to find operands where the last stem:[k] bits have a desired value, we only need to solve

[stem]
++++
\left\lfloor\frac{a\cdot2^n}{b}\right\rfloor \bmod{2^k} = \mathit{target}.
++++

We can do this with the following lifting identity:
[stem]
++++
\left\lfloor\frac{a}{b}\right\rfloor \bmod{m} = \left\lfloor\frac{a \bmod{bm}}{b}\right\rfloor
++++

Then, expanding the floor into an inequality yields:
[stem]
++++
b\cdot \mathit{target} \le a \bmod{bm} < b \cdot (\mathit{target} + 1)
++++

Substituting back in the original values gives
[stem]
++++
b \cdot \mathit{target} \le a\cdot 2^n \bmod 2^kb < b\cdot(\mathit{target} + 1),
++++
and simplifying yields
[stem]
++++
\frac{b}{2^k} \cdot \mathit{target} \le a \cdot 2^{n-k} \bmod b < \frac{b}{2^k}\cdot(\mathit{target}+1).
++++

The number of possible values for this inequality is very constrained for maximal stem:[k], so if stem:[a\cdot 2^{n-k} \equiv c \pmod{b}], then
[stem]
++++
a \equiv c \cdot 2^{-(n-k)} \pmod{b}.
++++

This is fairly trivial to solve, and frequently gives answers that fit constraints on significand lengths.

=== Multiplication

Multiplication uses a much simpler modular arithmetic approach. In essence, we are asked to solve stem:[ab \equiv c \pmod{2^k}] where stem:[k] is the number of extra bits. This has the simple solution stem:[a\equiv cb^{-1} \pmod{2^k}]. Implementing a solver for this and checking that significands are of the right size creates the desired significands.

=== Addition/Subtraction

The most number of extra bits are generated by placing the second addend or subtrahend in the lsb, guard, or one past the guard bit depending on the setup. For subtractions, because we rely on carries to set bits as we want, we get an additional bit of leeway for our mantissa placement. Guard = 1 cases can go one past the guard bit, and guard = 0 cases place the leading one in the guard bit. For addition, we place the leading one in the guard if it is a guard = 1 case, and otherwise it goes in the lsb of the other operand.

=== FMA

These cases are similar to the addition/subtraction cases, except the leading one of the third operand is always placed in the last digit of the multiplication result, and the multiplication result is constrained using the exact same method as the multiplication tests to give the desired pattern.

=== Converts

For these cases, we simply track where the LSB, Guard, and Sticky end up being for a convert, and place bits accordingly. For int to float converts, we also set the most significant bit of the int to ensure that a maximum number of bits end up in extra bits.

== Test Count Breakdown

For each arithmetic op, we have 8 cases for each combination of sign, lsb, and guard. We then have 7 different cases of extra bits, and 5 and formats rounding modes to run through. This totals 1400 per operation, and across 8 operations, we have 11200 tests.

For the converts, there are again 8 cases for each combination of sign, lsb, and guard with 7 cases of extra bits. Between the signed formats, this results in 27 narrowing conversions. For unsigned formats, we do not test any combination of the sign bit. So, between a signed and unsigned format there are 17 narrowing conversions. Across 45 rounding modes, this gives 9940 combinations. But, a convert between F16 and BF16 can only take on 2 of the extra bits patterns, losing 200 cases, for a total of 9740 cases.

This brings the total test count to 20940 tests.
